// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs1rdxR2SCikJPtVG2QdQ9Cp3Emjrxxqs',
    appId: '1:90175630651:web:66d0d70fef09072607db1e',
    messagingSenderId: '90175630651',
    projectId: 'chatapp-4ae16',
    authDomain: 'chatapp-4ae16.firebaseapp.com',
    storageBucket: 'chatapp-4ae16.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrT2BpBIkUFqS3bs_lKp353TQ1wqen62w',
    appId: '1:90175630651:android:40343e09fe0a71fe07db1e',
    messagingSenderId: '90175630651',
    projectId: 'chatapp-4ae16',
    storageBucket: 'chatapp-4ae16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-O0hiUHXMBv-ld_ysoU3TDLti8UvQcbw',
    appId: '1:90175630651:ios:79aa74b652cade4007db1e',
    messagingSenderId: '90175630651',
    projectId: 'chatapp-4ae16',
    storageBucket: 'chatapp-4ae16.firebasestorage.app',
    iosBundleId: 'com.example.g11chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-O0hiUHXMBv-ld_ysoU3TDLti8UvQcbw',
    appId: '1:90175630651:ios:79aa74b652cade4007db1e',
    messagingSenderId: '90175630651',
    projectId: 'chatapp-4ae16',
    storageBucket: 'chatapp-4ae16.firebasestorage.app',
    iosBundleId: 'com.example.g11chatApp',
  );
}
